/**
 * Helpers for the built-in icon library (game-icons.net set under
 * `public/icons/`). Pure functions only - no DOM, no fetch, no signals
 * - so the picker, schema validators, and tests can all share the
 * same resolution + search behaviour.
 *
 * Manifest shape lives in `public/icons/index.json` (generated by
 * `scripts/build-icons.mjs`).
 */

const URL_PATTERN = /(?:^|\/)icons\/(dark|light)\/[^/]+\/[^/]+\.svg$/;

function resolveBase(base) {
  if (typeof base !== 'string') return '/';
  if (base === '') return '/';
  if (!base.endsWith('/')) return base + '/';
  return base;
}

function getEnvBase() {
  try {
    if (typeof import.meta !== 'undefined' && import.meta.env?.BASE_URL) {
      return import.meta.env.BASE_URL;
    }
  } catch {
    // import.meta unavailable in some test contexts
  }
  return '/';
}

/**
 * Build the static URL for an icon. `id` is `<author>/<name>` (no
 * extension). `theme` defaults to dark; `base` defaults to the Vite
 * BASE_URL.
 */
export function builtinIconUrl(id, theme = 'dark', base) {
  const t = theme === 'light' ? 'light' : 'dark';
  const b = resolveBase(base ?? getEnvBase());
  return `${b}icons/${t}/${id}.svg`;
}

/**
 * Cheap check: does this URL point at our built-in icon library?
 * Used by render code that wants to know whether the URL is safe to
 * use as-is vs. needing mxc:// resolution etc.
 */
export function isBuiltinIconUrl(url) {
  if (typeof url !== 'string' || url === '') return false;
  if (url.startsWith('mxc://') || /^[a-z]+:\/\//i.test(url)) return false;
  return URL_PATTERN.test(url);
}

/**
 * Search the manifest. Returns up to `limit` icons matching the
 * query (against name + tags) and optional category/author filters.
 *
 * Ranking: exact-name (1) > name-prefix (2) > name-substring (3) >
 * tag-exact (4) > tag-substring (5). Stable within a tier.
 */
export function searchIcons(manifest, query, opts = {}) {
  const { category, author, limit = 200 } = opts;
  const icons = Array.isArray(manifest?.icons) ? manifest.icons : [];
  const q = (query ?? '').toString().trim().toLowerCase();

  const filtered = [];
  for (const icon of icons) {
    if (category && !(icon.categories?.includes(category))) continue;
    if (author && icon.author !== author) continue;
    if (!q) {
      filtered.push({ icon, rank: 0 });
      continue;
    }
    const name = (icon.name ?? '').toLowerCase();
    const tags = Array.isArray(icon.tags) ? icon.tags : [];
    let rank = -1;
    if (name === q) rank = 1;
    else if (name.startsWith(q)) rank = 2;
    else if (name.includes(q)) rank = 3;
    else if (tags.some((t) => String(t).toLowerCase() === q)) rank = 4;
    else if (tags.some((t) => String(t).toLowerCase().includes(q))) rank = 5;
    if (rank > 0) filtered.push({ icon, rank });
  }

  filtered.sort((a, b) => a.rank - b.rank);
  return filtered.slice(0, limit).map(({ icon }) => icon);
}

let _manifestPromise = null;
let _manifestCache = null;

/**
 * Fetch and memoise the icon manifest. First call kicks off the
 * request; subsequent calls return the same promise / cached value.
 */
export function loadIconManifest(base) {
  if (_manifestCache) return Promise.resolve(_manifestCache);
  if (_manifestPromise) return _manifestPromise;
  const b = resolveBase(base ?? getEnvBase());
  _manifestPromise = fetch(`${b}icons/index.json`)
    .then((r) => {
      if (!r.ok) throw new Error(`icon manifest fetch failed: ${r.status}`);
      return r.json();
    })
    .then((m) => {
      _manifestCache = m;
      _manifestPromise = null;
      return m;
    })
    .catch((err) => {
      _manifestPromise = null;
      throw err;
    });
  return _manifestPromise;
}

// Test-only reset
export function _resetIconManifestCache() {
  _manifestPromise = null;
  _manifestCache = null;
}
