#!/usr/bin/env bash
#
# package.sh - build MatrixVTT and bundle a deployable artifact for a static
# host (Caddy, nginx, any file server). Produces:
#
#   release/matrixvtt-<version>-<basetag>.tar.gz   (the dist/ tree at archive root)
#   release/matrixvtt-<version>-<basetag>.sha256
#   release/Caddyfile                              (ready to edit + drop in)
#
# Usage:
#   scripts/package.sh <url> [--out release] [--skip-smoke]
#   scripts/package.sh nondescript.design/mvtt
#   scripts/package.sh https://vtt.example.com
#
# Just give it the URL the app will live at - the domain and base path are
# derived from it (scheme optional). Overrides: --domain, --base, --out.
# Env equivalents: VITE_BASE, DOMAIN, OUT, SKIP_SMOKE=1
#
set -euo pipefail

cd "$(dirname "$0")/.."

BASE="${VITE_BASE:-/}"
DOMAIN="${DOMAIN:-vtt.example.com}"
OUT="${OUT:-release}"
SKIP_SMOKE="${SKIP_SMOKE:-}"
URL=""
base_set="" ; domain_set=""

while [ $# -gt 0 ]; do
  case "$1" in
    --base)   BASE="$2"; base_set=1; shift 2 ;;
    --domain) DOMAIN="$2"; domain_set=1; shift 2 ;;
    --url)    URL="$2"; shift 2 ;;
    --out)    OUT="$2"; shift 2 ;;
    --skip-smoke) SKIP_SMOKE=1; shift ;;
    -h|--help) sed -n '2,17p' "$0"; exit 0 ;;
    --*) echo "unknown flag: $1" >&2; exit 2 ;;
    *) # bare positional → the deploy URL
       if [ -n "$URL" ]; then echo "unexpected arg: $1" >&2; exit 2; fi
       URL="$1"; shift ;;
  esac
done

# Derive domain + base from the URL (host/path), unless explicitly overridden.
if [ -n "$URL" ]; then
  u="${URL#http://}"; u="${u#https://}"   # drop scheme if present
  u="${u%/}"                              # drop one trailing slash
  host="${u%%/*}"                         # everything up to the first '/'
  if [ "$u" = "$host" ]; then path="/"; else path="/${u#*/}/"; fi
  [ -n "$domain_set" ] || DOMAIN="$host"
  [ -n "$base_set" ]   || BASE="$path"
fi

# Normalize base to a leading+trailing slash (Vite expects "/" or "/foo/").
case "$BASE" in /*) ;; *) BASE="/$BASE" ;; esac
case "$BASE" in */) ;; *) BASE="$BASE/" ;; esac

VERSION="$(node -p "require('./package.json').version")"
# Tag for the filename: "root" for "/", else the path with slashes → dashes.
if [ "$BASE" = "/" ]; then BASETAG="root"; else BASETAG="$(echo "$BASE" | sed 's#^/##; s#/$##; s#/#-#g')"; fi
ARTIFACT="matrixvtt-${VERSION}-${BASETAG}.tar.gz"

# Absolute origin for robots.txt/sitemap.xml (deployMetaPlugin).
export SITE_ORIGIN="https://${DOMAIN}"

echo "▸ Building MatrixVTT v${VERSION} for base '${BASE}'"
VITE_BASE="$BASE" npm run build

# Docs build comes second: vite build empties dist/, and VitePress
# emits into dist/docs. The app's sidebar links to <base>docs/, so the
# archive must carry the site.
echo "▸ Building docs site for '${BASE}docs/'"
VITE_BASE="$BASE" npm run docs:build
[ -f dist/docs/index.html ] || { echo "docs build produced no dist/docs/index.html" >&2; exit 1; }

if [ -z "$SKIP_SMOKE" ]; then
  echo "▸ Verifying the build serves from '${BASE}' (smoke test)"
  VITE_BASE="$BASE" SITE_ORIGIN="$SITE_ORIGIN" npm run test:smoke
else
  echo "▸ Skipping smoke test (--skip-smoke)"
fi

mkdir -p "$OUT"

echo "▸ Archiving dist/ → ${OUT}/${ARTIFACT}"
tar -czf "${OUT}/${ARTIFACT}" -C dist .
( cd "$OUT" && sha256sum "$ARTIFACT" > "${ARTIFACT%.tar.gz}.sha256" )

# --- generate a Caddyfile ----------------------------------------------------
# Security header (mirrors the in-HTML CSP meta): connect-src stays open to any
# homeserver, wasm-unsafe-eval for the Matrix crypto wasm; fonts are self-hosted.
CSP="default-src 'self'; script-src 'self' 'unsafe-inline' 'wasm-unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https:; font-src 'self' data:; connect-src 'self' https: wss:; worker-src 'self' blob:; object-src 'none'; base-uri 'self'; form-action 'self'"

if [ "$BASE" = "/" ]; then
  cat > "${OUT}/Caddyfile" <<CADDY
# MatrixVTT - generated by scripts/package.sh (base ${BASE}, v${VERSION}).
# Extract the tarball into the 'root' path below, then: caddy reload
${DOMAIN} {
    root * /srv/matrixvtt
    encode zstd gzip

    @assets path /assets/*
    header @assets Cache-Control "public, max-age=31536000, immutable"

    @nocache path / /*.html /sw.js /health.json
    header @nocache Cache-Control "no-cache"

    # Open the bare domain on the standalone app (not the Element widget
    # index.html). Remove this line if you also embed the widget at /.
    rewrite / /app.html

    header {
        Content-Security-Policy "${CSP}"
        X-Content-Type-Options "nosniff"
        Referrer-Policy "strict-origin-when-cross-origin"
        -Server
    }

    handle_errors {
        rewrite * /404.html
        file_server
    }
    file_server
}
CADDY
else
  cat > "${OUT}/Caddyfile" <<CADDY
# MatrixVTT - generated by scripts/package.sh (base ${BASE}, v${VERSION}).
#
# ${DOMAIN} is presumably an existing site, so this is a SNIPPET to MERGE
# INTO your existing \`${DOMAIN} { ... }\` block - do NOT add a second site
# block for the same domain (Caddy will reject it), and do NOT add a root
# \`redir\` (it would hijack your homepage). The app lives only under ${BASE}.

    # bare /mvtt → /mvtt/ so the trailing-slash form matches handle_path.
    redir ${BASE%/} ${BASE%/}/

    handle_path ${BASE%/}/* {
        root * /srv/matrixvtt
        # /mvtt/ opens the standalone app (not the Element widget index.html).
        rewrite / /app.html
        @assets path /assets/*
        header @assets Cache-Control "public, max-age=31536000, immutable"
        @nocache path /*.html /sw.js /health.json
        header @nocache Cache-Control "no-cache"
        header {
            Content-Security-Policy "${CSP}"
            X-Content-Type-Options "nosniff"
            Referrer-Policy "strict-origin-when-cross-origin"
        }
        handle_errors {
            rewrite * /404.html
            file_server
        }
        file_server
    }
CADDY
fi

echo ""
echo "✓ Packaged:"
echo "    ${OUT}/${ARTIFACT}"
echo "    ${OUT}/${ARTIFACT%.tar.gz}.sha256"
echo "    ${OUT}/Caddyfile   (edit the domain '${DOMAIN}' and root path)"
echo ""
echo "Deploy:"
echo "    scp ${OUT}/${ARTIFACT} you@host:/tmp/"
echo "    ssh you@host 'sudo mkdir -p /srv/matrixvtt && sudo tar -xzf /tmp/${ARTIFACT} -C /srv/matrixvtt'"
echo "    # merge/copy the Caddyfile, then: sudo caddy reload --config /etc/caddy/Caddyfile"
echo "    # verify: curl -s https://${DOMAIN}${BASE}health.json   (app: https://${DOMAIN}${BASE})"
